## YAML Template.
---
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tx1
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass123
    ports:
      - "3309:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
